<a href="https://colab.research.google.com/github/matheusfantoni/inteligencia_artificial_praticas/blob/master/Regress%C3%A3o_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv("AnaliseEstudo.csv", sep = ';')

In [10]:
dataset.head()

Idade  TempoEstudo  Faltas  Prova1  Prova2  Prova3
0     18            2       4       0      11      11
1     17            2       2       9      11      11
2     15            2       6      12      13      12
3     15            3       0      14      14      14
4     16            2       0      11      13      13

In [12]:
col = dataset.loc[: , "Prova1":"Prova3"]
print(col)

     Prova1  Prova2  Prova3
0         0      11      11
1         9      11      11
2        12      13      12
3        14      14      14
4        11      13      13
..      ...     ...     ...
644      10      11      10
645      15      15      16
646      11      12       9
647      10      10      10
648      10      11      11

[649 rows x 3 columns]


In [17]:
dataset['ProvaMedia'] = col.mean(axis=1)
print(dataset)

     Idade  TempoEstudo  Faltas  Prova1  Prova2  Prova3  ProvaMedia
0       18            2       4       0      11      11    7.333333
1       17            2       2       9      11      11   10.333333
2       15            2       6      12      13      12   12.333333
3       15            3       0      14      14      14   14.000000
4       16            2       0      11      13      13   12.333333
..     ...          ...     ...     ...     ...     ...         ...
644     19            3       4      10      11      10   10.333333
645     18            2       4      15      15      16   15.333333
646     18            2       6      11      12       9   10.666667
647     17            1       6      10      10      10   10.000000
648     18            1       4      10      11      11   10.666667

[649 rows x 7 columns]


In [73]:
######## MODELO A  - MÉDIA DAS PROVAS X IDADE
######## MODELO A: Variável X será Idade e Y será a média das provas

X = dataset.Idade.values.reshape(-1, 1)
Y = dataset.ProvaMedia.values.reshape(-1, 1)

linear_regressor = LinearRegression()
linear_regressor.fit(X, Y)

####Aplicação do Modelo###
linear_regressor.predict(np.array([[23]]))


array([[9.6825524]])

In [74]:
######## MODELO B  - MÉDIA DAS PROVAS X TEMPO DE ESTUDO
######## MODELO B: Variável X será Tempo de Estudo e Y será a média das provas

X = dataset.TempoEstudo.values.reshape(-1, 1)
Y = dataset.ProvaMedia.values.reshape(-1, 1)

linear_regressor = LinearRegression()
linear_regressor.fit(X, Y)


####Aplicação do Modelo###
linear_regressor.predict(np.array([[60]]))

array([[63.51882211]])

In [75]:
######## MODELO C  - MÉDIA DAS PROVAS X FALTAS
######## MODELO C: Variável X será Faltas e Y será a média das provas

X = dataset.Faltas.values.reshape(-1, 1)
Y = dataset.ProvaMedia.values.reshape(-1, 1)

linear_regressor = LinearRegression()
linear_regressor.fit(X, Y)


####Aplicação do Modelo###
linear_regressor.predict(np.array([[32]]))

array([[9.46192911]])